document.write("<h1>이것은 write함수 실습입니다.</h1>");
//document.write("<h2>II-eugene-II</h2>");
//document.write("<nav>");
//document.write("<ul>");
//document.write("<li><a href="#">Home</a></li>");
//document.write("<li><a href="#">Math</a></li>");
//document.write("<li><a href="#">Code</a></li>");
//document.write("<li><a href="#">Support</a></li>");
//document.write("</ul>");
//document.write("</nav>");
