document.write("<div class=\"container\">");
document.write("<h2>II-eugene-II Note</h2>");
document.write("<nav>");
document.write("<ul class=\"header-ull\">");
document.write("<li class=\"header-item\"><a href=\"/index.html\">Home</a></li>");
document.write("<li class=\"header-item\"><a href=\"/Math/math.html\">Math</a></li>");
document.write("<li class=\"header-item\"><a href=\"/Code/code.html\">Code</a></li>");
document.write("<li class=\"header-item\"><a href=\"/history.html\">History</a></li>");
document.write("</ul>");
document.write("</nav>");
document.write("</div>");
